### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

##### import numpy as np


###### 1. Write a NumPy program to find the missing data in a given array.

In [1]:
import numpy as np

In [8]:
### code here
print("Original array:")
ar=np.array([[3,2,'nan',1],[10,12,10,9],[5,'nan',1,'nan']],dtype='float')
print(ar)
print("Find the missing data of the said array:")
print(np.isnan(ar))

Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]
Find the missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


In [ ]:
## sample output

Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

Find the missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


##### 2. Write a NumPy program to check whether two arrays are equal (element wise) or not.

In [16]:
### code here 
print("Array-1:")
arr1=np.array([12,14,17,19])
print(arr1)
print("Array-2:")
arr2=np.array([12,14,17,19])
print(arr2)
print("check whether the two arrays are equal element-wise or not:")
if np.array_equal(arr1,arr2):
    print("Equal")
else:
    print("Not Equal")

Array-1:
[12 14 17 19]
Array-2:
[12 14 17 19]
check whether the two arrays are equal element-wise or not:
Equal


In [20]:
print("Array-1:")
arr3=np.array([0.5,1.5,0.2,2.6])
print(arr3)
print("Array-2:")
arr4=np.array([0.499999,1.500000,0.2,2.6])
print(arr4)
print("check whether the two arrays are equal element-wise or not:")
if np.array_equal(arr3,arr4):
    print("Equal")
else:
    print("Not Equal")

Array-1:
[0.5 1.5 0.2 2.6]
Array-2:
[0.499999 1.5      0.2      2.6     ]
check whether the two arrays are equal element-wise or not:
Not Equal


###### 3. Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.

In [9]:
## code here
print("Original array:")
xp=np.random.randint(0,16,(4,4))
print(xp)
print("New array after swapping first and last rows of the said array:")
print(np.flipud(xp))

Original array:
[[ 7  9  7  2]
 [ 3 13  2 14]
 [11 14 15  1]
 [12  2 12 15]]
New array after swapping first and last rows of the said array:
[[12  2 12 15]
 [11 14 15  1]
 [ 3 13  2 14]
 [ 7  9  7  2]]


In [ ]:
## sample output

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


###### 4. Write a NumPy program to convert a list and tuple into arrays.

In [27]:
#### code here
print("Array from list:")
list1=[2,5,6,8]
np.array(list1)

Array from list:


array([2, 5, 6, 8])

In [28]:
print("Array from tuple")
tup=((2,3,5,8))
np.array(tup)

Array from tuple


array([2, 3, 5, 8])

###### 5. Write a NumPy program to find common values between two arrays.

###### Common values between two Array -1D

In [42]:
### code here
print("Array-1")
vx1=np.array([5,6,8,9,7])
print(vx1)
print("Array-2")
vx2=np.array([4,6,3,9,5])
print(vx2)
print("Common values between two arrays:")
print(np.intersect1d(vx1,vx2))

Array-1
[5 6 8 9 7]
Array-2
[4 6 3 9 5]
Common values between two arrays:
[5 6 9]


##### Common values between two Array -2D

In [51]:
print("Array-1")
vx3=np.array([[3,5,6,8],[5,9,8,6]])
print(vx3)
print("Array-2")
vx4=np.array([[8,0,7,1],[1,3,5,4]])
print(vx4)
print("Common values between two arrays:")
print(np.intersect1d(vx3,vx4))

Array-1
[[3 5 6 8]
 [5 9 8 6]]
Array-2
[[8 0 7 1]
 [1 3 5 4]]
Common values between two arrays:
[3 5 8]


###### 6. Write a NumPy program to create a new shape to an array without changing its data.

In [55]:
### code here
print("Original Data:")
sc=np.arange(1,7)
print(sc)
print("Reshape 3x2:")
print(sc.reshape(3,2))
print("Reshape 2x3:")
print(sc.reshape(2,3))

Original Data:
[1 2 3 4 5 6]
Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
[[1 2 3]
 [4 5 6]]


In [ ]:
### sample output

Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
[[1 2 3]
 [4 5 6]]


###### 7. Write a NumPy program to count the frequency of unique values in numpy array.

In [64]:
### code here
print("Original array:")
az=np.array([10,10,20,10,20,20,20,30,30,50,40,40])
print(az)
unique_value=np.unique(az,return_counts=True)
frequency=np.array(unique_value)
print("Frequency of unique values of the said array:")
print(frequency)

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


In [ ]:
## sample output

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


###### 8. Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).

In [70]:
### code here
print("Original arrays:")
print("Array-1")
ax=np.array([[0,0,0],[1,2,3],[4,5,6]])
print(ax)
print("Array-2")
ax1=np.array([10,11,12])
print(ax1)
print("\nNew Array:")
print(ax+ax1)

Original arrays:
Array-1
[[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2
[10 11 12]

New Array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


In [ ]:
## sample output

Original arrays:
Array-1
[[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2
[10 11 12]

New Array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


###### 9. Write a NumPy program to extract all the elements of the second row from a given (4x4) array.

In [72]:
### code here
arra_data = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(arra_data)
print("\nExtracted data: Second row")
print(arra_data[1])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


In [ ]:
import numpy as np
arra_data = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(arra_data)
print("\nExtracted data: Second row")
print(arra_data[1,:])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


###### 10. Write a NumPy program to extract third and fourth elements of the first and second rows from a given (4x4) array.

In [73]:
## code here
arra_data = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(arra_data)
print("\nExtracted data: Third and fourth elements of the first and second rows :")
print(arra_data[0:2,2:4])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows :
[[2 3]
 [6 7]]


In [ ]:
## sample output


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows 
[[2 3]
 [6 7]]


###### 11. Write a NumPy program to get the dates of yesterday, today and tomorrow.

In [74]:
### code here
import numpy as np
import datetime

In [78]:
today=np.datetime64('today')
yesterday= today - np.timedelta64(1,'D')
tomorrow =today + np.timedelta64(1,'D')
print("Yesterday's date:",yesterday)
print("Today's date:",today)
print("Tommorow's date:",tomorrow)

Yesterday's date: 2023-04-27
Today's date: 2023-04-28
Tommorow's date: 2023-04-29


###### 12. Write a NumPy program to find the first Monday in May 2017.

In [79]:
## code here
print("First Monday in May 2017:")
print(np.busday_offset('2017-05', 0, roll='forward', weekmask='Mon'))


First Monday in May 2017:
2017-05-01


In [ ]:
## sample output

First Monday in May 2017:
2017-05-01
